package generator;

import orm.Db;
import php.Global;
import php.Syntax;
import php.TypedArray;
using php.StringToolsNative;

class OrmManagerGenerator 
{
	public function new() {}
	
	public function make(db:Db, table:OrmTable, customOrmClassName:String, srcPath:String, positions:OrmPositions) : Void
	{
		Log.start(table.tableName + " => " + table.customManagerClassName);
		
		var vars = OrmTools.fields2vars(table.tableName, db.connection.getFields(table.tableName), positions);
		
		var autoGeneratedManager = getAutogenManager(db, table.tableName, vars, table.customModelClassName, table.autogenManagerClassName, customOrmClassName, positions);
		var destFileName = srcPath + table.autogenManagerClassName.replace('.', '/') + '.hx';
		Global.mkdir(Global.dirname(destFileName));
		Global.file_put_contents(
			 destFileName
			,"// This is autogenerated file. Do not edit!\n\n" + autoGeneratedManager.toString()
		);
		
		if (!Global.file_exists(srcPath + "/" + table.customManagerClassName.replace('.', '/') + '.hx'))
		{
			var customManager = getCustomManager(table.tableName, vars, table.customModelClassName, table.customManagerClassName, table.autogenManagerClassName);
			var destFileName = srcPath + table.customManagerClassName.replace('.', '/') + '.hx';
			Global.mkdir(Global.dirname(destFileName));
			Global.file_put_contents(destFileName, customManager.toString());
		}
		
		Log.finishSuccess();
	}
	
	function getAutogenManager(db:Db, table:String, vars:TypedArray<OrmPhpVar>, modelClassName:String, autogenManagerClassName:String, customOrmClassName:String, positions:OrmPositions) : PhpClass
	{
		var model:PhpClass = new PhpClass(autogenManagerClassName);
		
		model.addVar({ haxeName:"db", haxeType:"orm.Db", haxeDefVal:null }, true);
		model.addVar({ haxeName:"orm", haxeType:customOrmClassName, haxeDefVal:null }, true);
		model.addVar({ haxeName:"query(get, never)", haxeType:"orm.SqlQuery<" + modelClassName + ">", haxeDefVal:null });
		
		model.addMethod
		(
			'get_query',
			new TypedArray<PhpVar>(),
			'orm.SqlQuery<' + modelClassName + '>',
			"return new orm.SqlQuery<" + modelClassName + ">(\"" + table + "\", db, this);",
			true
		);
		
		model.addMethod
		(
			  "new"
			, Syntax.arrayDecl( 
				  { haxeName:"db", haxeType:"orm.Db", haxeDefVal:null } 
				, { haxeName:"orm", haxeType:customOrmClassName, haxeDefVal:null } 
			  )
			, "Void"
			, "this.db = db;\nthis.orm = orm;"
		);
        
        model.addMethod
		(
			'newModelFromParams',
			vars,
			modelClassName,
			  "var _obj = new " + modelClassName + "(db, orm);\n"
			+ vars.map(function(x) return '_obj.' + x.haxeName + ' = ' + x.haxeName + ';').join('\n') + "\n"
			+ "return _obj;",
			true
		);
		
		model.addMethod
		(
			'newModelFromRow',
			Syntax.arrayDecl(OrmTools.createVar('d', 'Dynamic')),
			modelClassName,
			  "var _obj = new " + modelClassName + "(db, orm);\n"
			+ vars.map(function(x) return '_obj.' + x.haxeName + " = Reflect.field(d, '" + x.haxeName + "');").join('\n') + "\n"
			+ "return _obj;"
			, true
		);
		
		model.addMethod
		(
			'where',
			Syntax.arrayDecl(OrmTools.createVar('field', 'String'), OrmTools.createVar('op', 'String'), OrmTools.createVar('value', 'Dynamic')),
			'orm.SqlQuery<' + modelClassName + '>',
			"return query.where(field, op, value);"
		);
		
		var getVars = vars.filter(function(x) return x.isKey);
		if (getVars.length > 0)
		{
			model.addMethod
			(
				'get',
				getVars,
				modelClassName,
				"return getBySqlOne('SELECT * FROM `" + table + "`" + getWhereSql(getVars) + ");"
			);
		}
		
		var createVars = vars.filter(function(x) return !x.isAutoInc);
		
		model.addMethod
		(
			'create',
			createVars,
			modelClassName,
			createVars.filter(positions.is).map
			(
				function(x) return 
				  "if (" + x.haxeName + " == null)\n"
				+ "{\n"
				+ "\tposition = db.query('SELECT MAX(`" + x.name + "`) FROM `" + table + "`" 
					+ getWhereSql(getForeignKeyVars(db, table, vars))
					+ ").getIntResult(0) + 1;\n"
				+ "}\n\n"
			).join("")
			+"db.query('INSERT INTO `" + table + "`("
				+ createVars.map(function(x) return "`" + x.name + "`").join(", ")
			+") VALUES (' + "
				+ createVars.map(function(x) return "db.quote(" + x.haxeName + ")").join(" + ', ' + ")
			+" + ')');\n"
			+"return newModelFromParams(" + vars.map(function(x) return x.isAutoInc ? 'db.lastInsertId()' : x.haxeName).join(", ") + ");"
		);
		
		model.addMethod
		(
			'createNamed',
			Syntax.arrayDecl(OrmTools.createVar("data", "{ " + createVars.map(function(x) return x.haxeName + ":" + x.haxeType).join(", ") + " }")),
			modelClassName,
			createVars.filter(function(x) return positions.is(x)).map
			(
				function(x) return 
				"if (data." + x.haxeName + " == null)\n"
				+ "{\n"
				+ "\tdata." + x.haxeName + " = db.query('SELECT MAX(`" + x.name + "`) FROM `" + table + "`" 
					+ getWhereSql(getForeignKeyVars(db, table, vars))
					+ ").getIntResult(0) + 1;\n"
				+ "}\n\n"
			).join("")
			+"db.query('INSERT INTO `" + table + "`("
				+ createVars.map(function(x) return "`" + x.name + "`").join(", ")
			+") VALUES (' + "
				+ createVars.map(function(x) return "db.quote(data." + x.haxeName + ")").join(" + ', ' + ")
			+" + ')');\n"
			+"return newModelFromParams(" + vars.map(function(x) return x.isAutoInc ? 'db.lastInsertId()' : "data." + x.haxeName).join(", ") + ");"
		);
		
		var dataVars: TypedArray<PhpVar> = Syntax.arrayDecl(OrmTools.createVar("data", "{ " + createVars.map(function(x) return (x.isKey ? "" : "?") + x.haxeName + ":" + x.haxeType).join(", ") + " }"));
		
		if (vars.exists(function(x) return x.isKey))
		{
			model.addMethod
			(
				'createOptional',
				dataVars,
				modelClassName,
				 "createOptionalNoReturn(data);\n"
				+"return get(" + getVars.map(function(x) return x.isAutoInc ? 'db.lastInsertId()' : "data." + x.haxeName).join(", ") + ");"
			);
		}
		
		model.addMethod
		(
			'createOptionalNoReturn',
			dataVars,
			"Void",
			createVars.filter(function(x) return positions.is(x)).map
			(
				function(x) return 
				"if (data." + x.haxeName + " == null)\n"
				+ "{\n"
				+ "\tdata." + x.haxeName + " = db.query('SELECT MAX(`" + x.name + "`) FROM `" + table + "`" 
					+ getWhereSql(getForeignKeyVars(db, table, vars))
					+ ").getIntResult(0) + 1;\n"
				+ "}\n\n"
			).join("")
			+"var fields = [];\n"
			+"var values = [];\n"
			+createVars.map
			(
				function(x) return 
				x.isKey
					? "fields.push('`" + x.name + "`'); values.push(db.quote(data." + x.haxeName + "));\n"
					: "if (Reflect.hasField(data, '" + x.haxeName + "')) { fields.push('`" + x.name + "`'); values.push(db.quote(data." + x.haxeName + ")); }\n"
			).join("")
			+"db.query('INSERT INTO `" + table + "`(' + fields.join(\", \") + ') VALUES (' + values.join(\", \") + ')');\n"
		);
		
		var deleteVars = vars.filter(function(x) return x.isKey);
		if (deleteVars.length == 0) deleteVars = vars;
		model.addMethod
		(
			'delete',
			deleteVars,
			'Void',
			"db.query('DELETE FROM `" + table + "`" + getWhereSql(deleteVars) + " + ' LIMIT 1');"
		);
		
		model.addMethod
		(
			'getAll',
			Syntax.arrayDecl(OrmTools.createVar('_order', 'String', getOrderDefVal(vars, positions))),
			'Array<' + modelClassName + '>',
			"return getBySqlMany('SELECT * FROM `" + table + "`' + (_order != null ? ' ORDER BY ' + _order : ''));"
		);
		
		model.addMethod
		(
			'getBySqlOne',
			Syntax.arrayDecl(OrmTools.createVar('sql', 'String')),
			modelClassName,
			 "var rows = db.query(sql + ' LIMIT 1');\n"
			+"if (rows.length == 0) return null;\n"
			+"return newModelFromRow(rows.next());"
		);
		
		model.addMethod
		(
			'getBySqlMany',
			Syntax.arrayDecl(OrmTools.createVar('sql', 'String')),
			'Array<' + modelClassName + '>',
			 "var rows = db.query(sql);\n"
			+"var list : Array<" + modelClassName + "> = [];\n"
			+"for (row in rows)\n"
			+"{\n"
			+"	list.push(newModelFromRow(row));\n"
			+"}\n"
			+"return list;"
		);
		
        Syntax.foreach(db.connection.getUniques(table), function(_, fields)
		{
            var vs = vars.filter(function(x) return fields.hasValue(x.name));
			createGetByMethodOne(table, vars, modelClassName, vs, model);
		});
		
        Syntax.foreach(getForeignKeyVars(db, table, vars), function(_, v)
        {
            createGetByMethodMany(table, vars, modelClassName, Syntax.arrayDecl(v), model, positions);
        });
		
		return model;
	}
	
	function getCustomManager(table:String, vars:TypedArray<OrmPhpVar>, modelClassName:String, fullClassName:String, baseClassName:String=null) : PhpClass
	{
		var model = new PhpClass(fullClassName, baseClassName);
		
		model.addImport(modelClassName);
		
		return model;
	}
	
	function createGetByMethodOne(table:String, vars:TypedArray<OrmPhpVar>, modelClassName:String, whereVars:TypedArray<OrmPhpVar>, model:PhpClass) : Void
	{
		if (whereVars == null || whereVars.length == 0) return;
        
        model.addMethod
		(
			'getBy' + whereVars.map(function(x) return StringToolsEx.capitalize(x.haxeName)).join('And'),
			whereVars, 
			modelClassName,
			"return getBySqlOne('SELECT * FROM `" + table + "`" + getWhereSql(whereVars) + ");"
		);
	}
	
	function createGetByMethodMany(table:String, vars:TypedArray<OrmPhpVar>, modelClassName:String, whereVars:TypedArray<OrmPhpVar>, model:PhpClass, positions:OrmPositions) : Void
	{
		if (whereVars == null || whereVars.length == 0) return;

		model.addMethod
		(
			'getBy' + whereVars.map(function(v) return StringToolsEx.capitalize(v.haxeName)).join('And'),
			(cast whereVars:TypedArray<PhpVar>).concat(Syntax.arrayDecl(OrmTools.createVar('_order', 'String', getOrderDefVal(vars, positions)))), 
			'Array<' + modelClassName + '>',
			"return getBySqlMany('SELECT * FROM `" + table + "`" + getWhereSql(whereVars) + " + (_order != null ? ' ORDER BY ' + _order : ''));"
		);
	}
	
	function getOrderDefVal(vars:TypedArray<OrmPhpVar>, positions:OrmPositions) : String
	{
		var positionVar = vars.filter(function(x) return positions.is(x));
		return positionVar.length == 0 ? "null" : "'" + positionVar.map(function(x) return x.name).join(", ") + "'";
	}
    
    function getWhereSql(vars:TypedArray<OrmPhpVar>) : String
    {
        return vars.length > 0
            ? " WHERE " + vars.map(function(v) return "`" + v.name + "` = ' + db.quote(" + v.haxeName + ")").join("+ ' AND ")
            : "'";
    }
    
    function getForeignKeyVars(db:Db, table:String, vars:TypedArray<OrmPhpVar>) : TypedArray<OrmPhpVar>
    {
        var foreignKeys = db.connection.getForeignKeys(table);
        var foreignKeyVars = vars.filter(function(v)
		{
            return foreignKeys.exists(function(fk) return fk.key == v.name);
        });
        return foreignKeyVars;
    }

}