package generator;

import orm.Db;
import php.Global;
import php.TypedArray;
import php.Syntax;
using php.StringToolsNative;

class OrmQueryGenerator 
{
	public function new() {}
	
	public function make(db:Db, table:OrmTable, outPath:String, positions:OrmPositions) : Void
	{
		Log.start(table.tableName + " => " + table.queryClassName);
		
		var vars = OrmTools.fields2vars(table.tableName, db.connection.getFields(table.tableName), positions);
		
		var klass = getQueryClass(table.tableName, vars, table.queryClassName, table.customModelClassName, table.customManagerClassName);
		var destFileName = outPath + table.queryClassName.replace(".", "/") + ".php";
		Tools.mkdir(Global.dirname(destFileName));
		Global.file_put_contents(
			  destFileName
			, "<?php\n// This file is autogenerated. Do not edit!\n\n" + klass.toString()
		);
		
		Log.finishSuccess();
	}
	
	function getQueryClass(table:String, vars:TypedArray<OrmPhpVar>, queryClassName:String, customModelClassName:String, customManagerClassName:String) : PhpClass
	{
		var model = new PhpClass(queryClassName, "nanodb.orm.SqlQuery");
		
		// function new(table:String, db:Db, manager:Manager<T>)
		model.addMethod(
			  "__construct"
			, Syntax.arrayDecl(
				new PhpVar("db", Tools.toPhpType("nanodb.orm.Db")),
				new PhpVar("manager", Tools.toPhpType(customManagerClassName))
			  )
			, "void"
			, "super('" + table + "', $db, $manager);"
		);
		
		// function where(field:String, op:String, value:Dynamic) : SqlQuery<T>
		model.addMethod(
			"where",
			Syntax.arrayDecl(
				new PhpVar("field", "string"),
				new PhpVar("op", "string"),
				new PhpVar("value", null)
			),
			Tools.toPhpType(queryClassName),
			"return parent::where($field, $op, $value);"
		);
		
		//function orderAsc(value:Dynamic) : SqlQuery<T>
		model.addMethod(
			"orderAsc",
			Syntax.arrayDecl(
				new PhpVar("value", null)
			),
			Tools.toPhpType(queryClassName),
			"return parent::orderAsc($value);"
		);
		
		//function orderDesc(value:Dynamic) : SqlQuery<T>
		model.addMethod(
			"orderDesc",
			Syntax.arrayDecl(
				new PhpVar("value", null)
			),
			Tools.toPhpType(queryClassName),
			"return parent::orderDesc($value);"
		);
		
		//function findMany(?limit:Int, ?offset:Int) : TypedArray<T>
		model.addMethod(
			"findMany",
			Syntax.arrayDecl(
				new PhpVar("limit", "int", "null"),
				new PhpVar("offset", "int", "null")
			),
			Tools.toPhpType(customModelClassName) + "[]",
			"return parent::findMany($value);"
		);

		//function findOne() : T
		model.addMethod(
			"findOne",
			Syntax.arrayDecl(),
			Tools.toPhpType(customModelClassName),
			"return parent::findOne();"
		);
		
		return model;
	}
}