package generator;

using php.StringToolsNative;

class OrmTable
{
	public var tableName(default, null) : String;
	public var varName(default, null) : String;
	
	public var autogeneratedManagerClassName(default, null) : String;
	public var customManagerClassName(default, null) : String;
	
	public var autogeneratedModelClassName(default, null) : String;
	public var customModelClassName(default, null) : String;
	
	public var queryClassName : String;
	
	public function new(tableName:String, autogeneratedNamespace:String, customNamespace:String)
	{
		this.tableName = tableName;
		this.varName = getVarName();
		
		var className = Tools.pluralToSingular(getClassName());
		
		this.autogeneratedManagerClassName = autogeneratedNamespace + "." + className + "Manager";
		this.customManagerClassName = customNamespace + "." + className + "Manager";
		
		this.autogeneratedModelClassName = autogeneratedNamespace + "." + className;
		this.customModelClassName = customNamespace + "." + className;
		
		this.queryClassName = autogeneratedNamespace + "." + className + "Query";
	}
	
	function getVarName() : String
	{
		var s = "";
		
		var packs = tableName.toLowerCase().splitNative("__");
		while (packs.length > 1)
		{
			var pack = packs.shift();
			var words = pack.splitNative("_");
			s += words.shift();
			s += words.map(function(v) return Tools.capitalize(v)).join("");
			s += "_";
		}
		
		var parts = packs[0].splitNative("_");
		
		s += parts[0] + parts.slice(1).map(function(w) return Tools.capitalize(w)).join("");
		
		return s;
	}
	
	function getClassName() : String
    {
		var s = "";
		
		var packs = tableName.toLowerCase().splitNative("__");
		while (packs.length > 1)
		{
			var pack = packs.shift();
			var words = pack.splitNative("_");
			s += words.shift();
			s += words.map(function(x) return Tools.capitalize(x)).join("");
			s += ".";
		}
		
		s += packs[0].splitNative("_").map(function(x) return Tools.capitalize(x)).join("");
		
		return s;
    }
}