<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

namespace nanodb\orm;

use \nanodb\php\Boot;
use \nanodb\sys\db\ResultSet;

interface DbDriver {
	/**
	 * @return void
	 */
	public function close () ;

	/**
	 * @param string $table
	 * 
	 * @return mixed
	 */
	public function getFields ($table) ;

	/**
	 * @param string $table
	 * 
	 * @return mixed
	 */
	public function getForeignKeys ($table) ;

	/**
	 * @return mixed
	 */
	public function getTables () ;

	/**
	 * @param string $table
	 * 
	 * @return mixed
	 */
	public function getUniques ($table) ;

	/**
	 * @return int
	 */
	public function lastInsertId () ;

	/**
	 * @param string $sql
	 * 
	 * @return ResultSet
	 */
	public function query ($sql) ;

	/**
	 * @param mixed $s
	 * 
	 * @return string
	 */
	public function quote ($s) ;
}

Boot::registerClass(DbDriver::class, 'orm.DbDriver');
