<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

namespace nanodb\orm;

class DbException extends \Exception {
	/**
	 * @param string $message
	 * @param int $code
	 * @param \Throwable $previous
	 * 
	 * @return void
	 */
	public function __construct ($message = null, $code = null, $previous = null) {
		parent::__construct($message, $code, $previous);
	}
}

