<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

namespace nanodb\orm;

use \nanodb\php\Boot;

class DbTableFieldData {
	/**
	 * @var bool
	 */
	public $isAutoInc;
	/**
	 * @var bool
	 */
	public $isKey;
	/**
	 * @var bool
	 */
	public $isNull;
	/**
	 * @var string
	 */
	public $name;
	/**
	 * @var string
	 */
	public $type;

	/**
	 * @param string $name
	 * @param string $type
	 * @param bool $isNull
	 * @param bool $isKey
	 * @param bool $isAutoInc
	 * 
	 * @return void
	 */
	public function __construct ($name, $type, $isNull, $isKey, $isAutoInc) {
		$this->name = $name;
		$this->type = $type;
		$this->isNull = $isNull;
		$this->isKey = $isKey;
		$this->isAutoInc = $isAutoInc;
	}
}

Boot::registerClass(DbTableFieldData::class, 'orm.DbTableFieldData');
