<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

namespace nanodb\orm;

interface ISerializer {
	/**
	 * @param mixed $src
	 * @param mixed $dest
	 * @param mixed $properties
	 * 
	 * @return void
	 */
	public function deserializeObject ($src, $dest, $properties = null) ;

	/**
	 * @param mixed $src
	 * @param mixed $properties
	 * 
	 * @return mixed
	 */
	public function serializeObject ($src, $properties = null) ;
}

