<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

namespace nanodb\orm;

use \nanodb\orm\ISerializer as OrmISerializer;

class Serializer implements OrmISerializer {
	/**
	 * @param mixed $src
	 * @param mixed $dest
	 * @param mixed $properties
	 * 
	 * @return void
	 */
	public function deserializeObject ($src, $dest, $properties = null) {
		if ($properties === null) {
			$properties = array_keys(get_object_vars($dest));
		}
		foreach ($properties as $key => $value) {
			$tmp = $dest;
			$tmp->{$value} = $src[$value];
		}
	}

	/**
	 * @param mixed $src
	 * @param mixed $properties
	 * 
	 * @return mixed
	 */
	public function serializeObject ($src, $properties = null) {
		if ($properties === null) {
			$properties = array_keys(get_object_vars($src));
		}
		$r = [];
		foreach ($properties as $key => $value) {
			$tmp = $src;
			$r[$value] = $tmp->{$value};

		}
		return $r;
	}
}

