<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

namespace nanodb\orm;

use \nanodb\orm\SqlTextField as OrmSqlTextField;
use \nanodb\orm\SqlTextRaw as OrmSqlTextRaw;
use \nanodb\orm\Db as OrmDb;
use \nanodb\sys\db\ResultSet;

class SqlQuery {
	/**
	 * @var mixed
	 */
	protected $conditions;
	/**
	 * @var OrmDb
	 */
	protected $db;
	/**
	 * @var object
	 */
	protected $manager;
	/**
	 * @var mixed
	 */
	protected $orderBys;
	/**
	 * @var string
	 */
	protected $table;

	/**
	 * @param string $table
	 * @param OrmDb $db
	 * @param object $manager
	 * 
	 * @return void
	 */
	public function __construct ($table, $db, $manager) {
		$this->orderBys = [];
		$this->conditions = [];
		$this->table = $table;
		$this->db = $db;
		$this->manager = $manager;
	}

	/**
	 * @return int
	 */
	public function count () {
		$r = $this->db->query("SELECT COUNT(*) FROM `" . $this->table . "`" . $this->getWhereSql());
		if (!$r->hasNext()) {
			return 0;
		}
		return $r->getIntResult(0);
	}

	/**
	 * @param int $limit
	 * @param int $offset
	 * 
	 * @return void
	 */
	public function delete ($limit = null, $offset = null) {
		$this->db->query("DELETE FROM `" . $this->table . "`" . $this->getWhereSql() . $this->getLimitSql($limit) . $this->getOffsetSql($offset));
	}

	/**
	 * @return bool
	 */
	public function exists () {
		return $this->findOneFields([$this->db->sqlTextRaw("1")]) !== null;
	}

	/**
	 * @param int $limit
	 * @param int $offset
	 * 
	 * @return mixed
	 */
	public function findMany (int $limit = null, int $offset = null) : array {
		$sqlSelect = $this->getSelectSql(null);
		$sqlLimit = $this->getLimitSql($limit);
		$sqlOffset = $this->getOffsetSql($offset);
		return $this->manager->getMany($sqlSelect . $sqlLimit . $sqlOffset);
	}

	/**
	 * @param mixed $fields
	 * @param int $limit
	 * @param int $offset
	 * 
	 * @return ResultSet
	 */
	public function findManyFields ($fields, $limit = null, $offset = null) {
		return $this->db->query($this->getSelectSql($fields) . $this->getLimitSql($limit) . $this->getOffsetSql($offset));
	}

	/**
	 * @return mixed
	 */
	public function findOne () {
		return $this->manager->getOne($this->getSelectSql(null));
	}

	/**
	 * @param mixed $fields
	 * 
	 * @return mixed
	 */
	public function findOneFields ($fields) {
		$rr = $this->db->query($this->getSelectSql($fields) . "\nLIMIT 1");
		if ($rr->hasNext()) {
			return $rr->next();
		}
		return null;
	}

	/**
	 * @param int $limit
	 * 
	 * @return string
	 */
	public function getLimitSql ($limit) {
		if ($limit !== null) {
			return "\nLIMIT " . $limit;
		} else {
			return "";
		}
	}

	/**
	 * @param int $offset
	 * 
	 * @return string
	 */
	public function getOffsetSql ($offset) {
		if ($offset !== null) {
			return "\nOFFSET " . $offset;
		} else {
			return "";
		}
	}

	/**
	 * @return string
	 */
	public function getOrderBySql () {
		if (count($this->orderBys) > 0) {
			return "\nORDER BY " . (implode(", ", $this->orderBys)??'null');
		} else {
			return "";
		}
	}

	/**
	 * @param mixed $fields
	 * 
	 * @return string
	 */
	public function getSelectSql ($fields) {
		$_gthis = $this;
		$f = ($fields !== null ? array_map(function ($x)  use (&$_gthis) {
			return $_gthis->quoteField($x);
		}, $fields) : ["*"]);
		return "SELECT " . (implode(", ", $f)??'null') . "\nFROM `" . $this->table . "`" . $this->getWhereSql() . $this->getOrderBySql();
	}

	/**
	 * @return string
	 */
	public function getWhereSql () {
		if (count($this->conditions) > 0) {
			return "\nWHERE " . (implode("\n\tAND ", $this->conditions)??'null');
		} else {
			return "";
		}
	}

	/**
	 * @param mixed $value
	 * 
	 * @return SqlQuery
	 */
	public function orderAsc ($value) {
		array_push($this->orderBys, $this->quoteValue($value));
		return $this;
	}

	/**
	 * @param mixed $value
	 * 
	 * @return SqlQuery
	 */
	public function orderDesc ($value) {
		array_push($this->orderBys, $this->quoteValue($value) . " DESC");
		return $this;
	}

	/**
	 * @param mixed $v
	 * 
	 * @return string
	 */
	public function quoteField ($v) {
		if (($v instanceof OrmSqlTextRaw)) {
			return $v->text;
		}
		if (($v instanceof OrmSqlTextField)) {
			return "`" . $v->text . "`";
		}
		return "`" . $v . "`";
	}

	/**
	 * @param mixed $v
	 * 
	 * @return string
	 */
	public function quoteValue ($v) {
		$_gthis = $this;
		if (($v instanceof OrmSqlTextRaw)) {
			return $v->text;
		}
		if (($v instanceof OrmSqlTextField)) {
			return "`" . $v->text . "`";
		}
		if (is_array($v)) {
			return "(" . (implode(", ", array_map(function ($x)  use (&$_gthis) {
				return $_gthis->db->quote($x);
			}, $v))??'null') . ")";
		}
		return $this->db->quote($v);
	}

	/**
	 * @param mixed $fields
	 * @param int $limit
	 * @param int $offset
	 * 
	 * @return void
	 */
	public function update ($fields, $limit = null, $offset = null) {
		$_gthis = $this;
		$sets = [];
		foreach ($fields as $key => $value) {
			array_push($sets, "`" . $key . "` = " . $_gthis->quoteValue($value));
		}
		$this->db->query("UPDATE `" . $this->table . "`\nSET\n\t" . (implode("\n\t", $sets)??'null') . $this->getWhereSql() . $this->getLimitSql($limit) . $this->getOffsetSql($offset));
	}

	/**
	 * @param string $rawSqlText
	 * 
	 * @return SqlQuery
	 */
	public function where (string $rawSqlText) {
		array_push($this->conditions, $rawSqlText);
		return $this;
	}

	/**
	 * @param string $field
	 * @param string $op
	 * @param mixed $value
	 * 
	 * @return SqlQuery
	 */
	public function whereField (string $field, string $op, $value) {
		$_gthis = $this;
		$opUC = trim(mb_strtoupper($op), null);
		if ($opUC === "!=" || $opUC === "<>") {
			if (($value === null)) {
				array_push($this->conditions, "`" . $field . "` IS NOT NULL");
			} else {
				array_push($this->conditions, "`" . $field . "` != " . $this->quoteValue($value));
			}
		} else if ($opUC === "=") {
			if (($value === null)) {
				array_push($this->conditions, "`" . $field . "` IS NULL");
			} else {
				array_push($this->conditions, "`" . $field . "` = " . $this->quoteValue($value));
			}
		} else if ($opUC === "IN" || $opUC === "NOT IN") {
			$this1 = [];
			$values = $this1;
			$collection = $value;
			foreach ($collection as $key => $value1) {
				array_push($values, $_gthis->quoteValue($value1));
			}

			array_push($this->conditions, "`" . $field . "` " . $opUC . " (" . (implode(", ", $values)??'null') . ")");
		} else {
			array_push($this->conditions, "`" . $field . "` " . $op . " " . $this->quoteValue($value));
		}
		return $this;
	}
}

