<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

namespace nanodb\orm;

use \nanodb\orm\SqlText as OrmSqlText;

class SqlTextField extends OrmSqlText {
	/**
	 * @param string $fieldName
	 * 
	 * @return void
	 */
	public function __construct ($fieldName) {
		parent::__construct($fieldName);
	}
}

