<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

namespace nanodb\orm;

use \nanodb\orm\SqlText as OrmSqlText;

class SqlTextRaw extends OrmSqlText {
	/**
	 * @param string $sqlText
	 * 
	 * @return void
	 */
	public function __construct ($sqlText) {
		parent::__construct($sqlText);
	}
}

