<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

namespace nanodb\php\_Boot;

use \nanodb\php\Boot;
use \nanodb\php\_Boot\HxException as _BootHxException;
use \nanodb\php\_Boot\HxAnon as _BootHxAnon;

/**
 * Closures implementation
 */
class HxClosure {
	/**
	 * @var mixed
	 * A callable value, which can be invoked by PHP
	 */
	public $callable;
	/**
	 * @var string
	 * Method name for methods
	 */
	public $func;
	/**
	 * @var mixed
	 * `this` for instance methods; php class name for static methods
	 */
	public $target;

	/**
	 * @param mixed $target
	 * @param string $func
	 * 
	 * @return void
	 */
	public function __construct ($target, $func) {
		$this->target = $target;
		$this->func = $func;
		if (is_null($target)) {
			throw new _BootHxException("Unable to create closure on `null`");
		}
		$tmp = null;
		if (($target instanceof _BootHxAnon)) {
			$tmp1 = $target;
			$tmp = $tmp1->{$func};
		} else {
			$tmp = [$target, $func];
		}
		$this->callable = $tmp;
	}

	/**
	 * @see http://php.net/manual/en/language.oop5.magic.php#object.invoke
	 * 
	 * @return mixed
	 */
	public function __invoke () {
		return call_user_func_array($this->callable, func_get_args());
	}

	/**
	 * Invoke this closure with `newThis` instead of `this`
	 * 
	 * @param mixed $newThis
	 * @param mixed $args
	 * 
	 * @return mixed
	 */
	public function callWith ($newThis, $args) {
		return call_user_func_array($this->getCallback($newThis), $args);
	}

	/**
	 * Check if this is the same closure
	 * 
	 * @param HxClosure $closure
	 * 
	 * @return bool
	 */
	public function equals ($closure) {
		if (Boot::equal($this->target, $closure->target)) {
			return $this->func === $closure->func;
		} else {
			return false;
		}
	}

	/**
	 * Generates callable value for PHP
	 * 
	 * @param mixed $eThis
	 * 
	 * @return mixed
	 */
	public function getCallback ($eThis = null) {
		if ($eThis === null) {
			$eThis = $this->target;
		}
		if (($eThis instanceof _BootHxAnon)) {
			$tmp = $eThis;
			return $tmp->{$this->func};
		}
		return [$eThis, $this->func];
	}
}

Boot::registerClass(HxClosure::class, 'php._Boot.HxClosure');
