<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

namespace nanodb\generator;

use \nanodb\php\Boot;

class FsTools {
	/**
	 * @param string $path
	 * 
	 * @return void
	 */
	static public function mkdir ($path) {
		if (!file_exists($path)) {
			mkdir($path, 511, true);
		}
	}
}

Boot::registerClass(FsTools::class, 'generator.FsTools');
