<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

namespace nanodb\generator;


/**
 * Global log class.
 * Using:
 *		Log.instance = new Log(5); // init log at the start of your application; 5 - nesting level limit (messages with greater nesting level will be ignored)
 * 		...
 *		Log.start("MyProcessStartMessage");
 * 		...
 * 		Log.echo("myMessage");
 * 		...
 * 		if (good) Log.finishSuccess(); // finish Process
 * 		else      Log.finishFail();
 */
class Log {
	/**
	 * @var Log
	 */
	static public $instance;

	/**
	 * @var int
	 */
	public $depth;
	/**
	 * @var int
	 */
	public $depthLimit;
	/**
	 * @var bool
	 */
	public $inBlock;
	/**
	 * @var int
	 */
	public $ind;
	/**
	 * @var int
	 */
	public $levelLimit;
	/**
	 * @var mixed
	 */
	public $shown;

	/**
	 * @param string $message
	 * @param int $level
	 * 
	 * @return void
	 */
	static public function echo ($message, $level = 1) {
		if ($level === null) {
			$level = 1;
		}
		if (Log::$instance !== null) {
			Log::$instance->echoInner($message, $level);
		}
	}

	/**
	 * @param string $text
	 * 
	 * @return void
	 */
	static public function finishFail ($text = "FAIL") {
		if ($text === null) {
			$text = "FAIL";
		}
		if (Log::$instance !== null) {
			Log::$instance->finishFailInner($text);
		}
	}

	/**
	 * @param string $text
	 * 
	 * @return void
	 */
	static public function finishSuccess ($text = "OK") {
		if ($text === null) {
			$text = "OK";
		}
		if (Log::$instance !== null) {
			Log::$instance->finishSuccessInner($text);
		}
	}

	/**
	 * @param string $message
	 * @param int $level
	 * @param \Closure $procFunc
	 * 
	 * @return void
	 */
	static public function process ($message, $level = 1, $procFunc) {
		if ($level === null) {
			$level = 1;
		}
		Log::start($message, $level);
		try {
			$procFunc();
		}
		catch (\Throwable $e) {
			Log::finishFail();
			throw $e;
		}
		Log::finishSuccess();
	}

	/**
	 * @param string $message
	 * @param int $level
	 * @param \Closure $procFunc
	 * 
	 * @return mixed
	 */
	static public function processResult ($message, $level = 1, $procFunc) {
		if ($level === null) {
			$level = 1;
		}
		Log::start($message, $level);
		$r = null;
		try {
			$r = $procFunc();
		}
		catch (\Throwable $e) {
			Log::finishFail();
			throw $e;
		}
		Log::finishSuccess();
		return $r;
	}

	/**
	 * @param string $message
	 * @param int $level
	 * 
	 * @return void
	 */
	static public function start ($message, $level = 1) {
		if ($level === null) {
			$level = 1;
		}
		if (Log::$instance !== null) {
			Log::$instance->startInner($message, $level);
		}
	}

	/**
	 * @param int $depthLimit
	 * @param int $levelLimit
	 * 
	 * @return void
	 */
	public function __construct ($depthLimit = 2147483647, $levelLimit = 2147483647) {
		if ($depthLimit === null) {
			$depthLimit = 2147483647;
		}
		if ($levelLimit === null) {
			$levelLimit = 2147483647;
		}
		$this->depthLimit = $depthLimit;
		$this->levelLimit = $levelLimit;
		$this->depth = -1;
		$this->ind = 0;
		$this->inBlock = false;
		$this->shown = [];
	}

	/**
	 * @param string $text
	 * @param int $level
	 * 
	 * @return void
	 */
	public function echoInner ($text, $level) {
		if ($this->depth < $this->depthLimit) {
			if ($level <= $this->levelLimit) {
				if ($this->inBlock) {
					$this->println("");
				}
				$this->println($this->indent($this->ind) . (str_replace("\n", "\n" . $this->indent($this->ind), $text)??'null'));
				$this->inBlock = false;
			}
		}
	}

	/**
	 * @param string $text
	 * 
	 * @return void
	 */
	public function finishFailInner ($text) {
		if ($this->depth < $this->depthLimit) {
			if (array_pop($this->shown)) {
				if (!$this->inBlock) {
					$this->print($this->indent($this->ind));
				}
				$this->ind--;
				if (!(mb_strpos($text, "\n") !== false)) {
					$this->println("[" . $text . "]");
				} else {
					$this->println("\n" . ($this->indent($this->ind + 1)??'null') . "[\n" . ($this->indent($this->ind + 2)??'null') . (str_replace("\n", "\n" . ($this->indent($this->ind + 2)??'null'), $text)??'null') . "\n" . ($this->indent($this->ind + 1)??'null') . "]");
				}
				$this->inBlock = false;
			}
		}
		$this->depth--;
	}

	/**
	 * @param string $text
	 * 
	 * @return void
	 */
	public function finishSuccessInner ($text) {
		if ($this->depth < $this->depthLimit) {
			if (array_pop($this->shown)) {
				if (!$this->inBlock) {
					$this->print($this->indent($this->ind));
				}
				$this->ind--;
				if (!(mb_strpos($text, "\n") !== false)) {
					$this->println("[" . $text . "]");
				} else {
					$this->println("\n" . ($this->indent($this->ind + 1)??'null') . "[\n" . ($this->indent($this->ind + 2)??'null') . (str_replace("\n", "\n" . ($this->indent($this->ind + 2)??'null'), $text)??'null') . "\n" . ($this->indent($this->ind + 1)??'null') . "]");
				}
				$this->inBlock = false;
			}
		}
		$this->depth--;
	}

	/**
	 * @param int $depth
	 * 
	 * @return string
	 */
	public function indent ($depth) {
		return str_pad("", $depth * 2, " ");
	}

	/**
	 * @param string $s
	 * 
	 * @return void
	 */
	public function print ($s) {
		echo($s);
	}

	/**
	 * @param string $s
	 * 
	 * @return void
	 */
	public function println ($s) {
		echo($s . "\n");
	}

	/**
	 * @param string $message
	 * @param int $level
	 * 
	 * @return void
	 */
	public function startInner ($message, $level) {
		$this->depth++;
		if ($this->depth < $this->depthLimit) {
			if ($level <= $this->levelLimit) {
				if ($this->inBlock) {
					$this->println("");
				}
				$this->print($this->indent($this->ind) . $message . ": ");
				$this->inBlock = true;
				array_push($this->shown, true);
				$this->ind++;
			} else {
				array_push($this->shown, false);
			}
		}
	}

	/**
	 * @internal
	 * @access private
	 */
	static public function __hx__init ()
	{
		static $called = false;
		if ($called) return;
		$called = true;

		self::$instance = new Log();
	}
}

Log::__hx__init();
