<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

namespace nanodb\generator;

use \nanodb\php\Boot;

class OrmPositions {
	/**
	 * @var mixed
	 */
	public $names;

	/**
	 * @param mixed $names
	 * 
	 * @return void
	 */
	public function __construct ($names) {
		$this->names = $names;
	}

	/**
	 * @param object $v
	 * 
	 * @return bool
	 */
	public function is ($v) {
		if (!(in_array($v->table . "." . $v->name, $this->names, false) || in_array("*." . $v->name, $this->names, false))) {
			return in_array($v->name, $this->names, false);
		} else {
			return true;
		}
	}
}

Boot::registerClass(OrmPositions::class, 'generator.OrmPositions');
