<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

namespace nanodb\generator;

use \nanodb\generator\Tools as GeneratorTools;

class OrmTable {
	/**
	 * @var string
	 */
	public $autogeneratedManagerClassName;
	/**
	 * @var string
	 */
	public $autogeneratedModelClassName;
	/**
	 * @var string
	 */
	public $customManagerClassName;
	/**
	 * @var string
	 */
	public $customModelClassName;
	/**
	 * @var string
	 */
	public $queryClassName;
	/**
	 * @var string
	 */
	public $tableName;
	/**
	 * @var string
	 */
	public $varName;

	/**
	 * @param string $tableName
	 * @param string $autogeneratedNamespace
	 * @param string $customNamespace
	 * 
	 * @return void
	 */
	public function __construct ($tableName, $autogeneratedNamespace, $customNamespace) {
		$this->tableName = $tableName;
		$this->varName = $this->getVarName();
		$className = GeneratorTools::pluralToSingular($this->getClassName());
		$this->autogeneratedManagerClassName = $autogeneratedNamespace . "." . $className . "Manager";
		$this->customManagerClassName = $customNamespace . "." . $className . "Manager";
		$this->autogeneratedModelClassName = $autogeneratedNamespace . "." . $className;
		$this->customModelClassName = $customNamespace . "." . $className;
		$this->queryClassName = $autogeneratedNamespace . "." . $className . "Query";
	}

	/**
	 * @return string
	 */
	public function getClassName () {
		$s = "";
		$packs = explode("__", mb_strtolower($this->tableName));
		while (count($packs) > 1) {
			$pack = array_shift($packs);
			$words = explode("_", $pack);
			$s = $s . array_shift($words);
			$s = $s . (implode("", array_map(function ($x) {
				return GeneratorTools::capitalize($x);
			}, $words))??'null');
			$s = $s . ".";
		}
		$s = $s . (implode("", array_map(function ($x1) {
			return GeneratorTools::capitalize($x1);
		}, explode("_", $packs[0])))??'null');
		return $s;
	}

	/**
	 * @return string
	 */
	public function getVarName () {
		$s = "";
		$packs = explode("__", mb_strtolower($this->tableName));
		while (count($packs) > 1) {
			$pack = array_shift($packs);
			$words = explode("_", $pack);
			$s = $s . array_shift($words);
			$s = $s . (implode("", array_map(function ($v) {
				return GeneratorTools::capitalize($v);
			}, $words))??'null');
			$s = $s . "_";
		}
		$parts = explode("_", $packs[0]);
		$s1 = implode("", array_map(function ($w) {
			return GeneratorTools::capitalize($w);
		}, array_slice($parts, 1, null)));
		$s = $s . ($parts[0]??'null') . $s1;
		return $s;
	}
}

