<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

namespace nanodb\generator;

use \nanodb\generator\Tools as GeneratorTools;
use \nanodb\generator\PhpVar as GeneratorPhpVar;

class PhpClass {
	/**
	 * @var string
	 */
	public $baseFullClassName;
	/**
	 * @var mixed
	 */
	public $customs;
	/**
	 * @var string
	 */
	public $fullClassName;
	/**
	 * @var mixed
	 */
	public $imports;
	/**
	 * @var mixed
	 */
	public $methods;
	/**
	 * @var mixed
	 */
	public $vars;

	/**
	 * @param string $fullClassName
	 * @param string $baseFullClassName
	 * 
	 * @return void
	 */
	public function __construct ($fullClassName, $baseFullClassName = null) {
		$this->fullClassName = $fullClassName;
		$this->baseFullClassName = $baseFullClassName;
		$this1 = [];
		$this->imports = $this1;
		$this2 = [];
		$this->vars = $this2;
		$this3 = [];
		$this->methods = $this3;
		$this4 = [];
		$this->customs = $this4;
	}

	/**
	 * @param string $code
	 * 
	 * @return void
	 */
	public function addCustom ($code) {
		array_push($this->customs, $code);
	}

	/**
	 * @param string $packageName
	 * 
	 * @return void
	 */
	public function addImport ($packageName) {
		array_push($this->imports, "use " . (GeneratorTools::toPhpType($packageName)??'null') . ";");
	}

	/**
	 * @param string $name
	 * @param mixed $vars
	 * @param string $retType
	 * @param string $body
	 * @param string $access
	 * @param bool $isStatic
	 * 
	 * @return void
	 */
	public function addMethod ($name, $vars, $retType, $body, $access = "public", $isStatic = false) {
		if ($access === null) {
			$access = "public";
		}
		if ($isStatic === null) {
			$isStatic = false;
		}
		$header = (((($retType !== null) && (mb_strpos($retType, "[]") !== false) ? "/**\n\x09 * @return " . $retType . "\n\x09 */\n\x09" : ""))??'null') . (($access . " ")??'null') . ((($isStatic ? "static " : ""))??'null') . "function " . $name . "(" . (implode(", ", array_map(function ($v) {
			return ((($v->haxeType !== null ? $v->haxeType . " " : ""))??'null') . "\$" . $v->haxeName . ((($v->haxeDefVal !== null ? "=" . $v->haxeDefVal : ""))??'null');
		}, $vars))??'null') . ")" . ((($retType !== null ? " : " . (((!(mb_strpos($retType, "[]") !== false) ? $retType : "array"))??'null') : ""))??'null');
		$s = $header . "\n" . "\x09{\n" . ($this->indent(trim($body, null), "\x09\x09")??'null') . "\n" . "\x09}";
		array_push($this->methods, $s);
	}

	/**
	 * @param GeneratorPhpVar $v
	 * @param bool $isStatic
	 * 
	 * @return void
	 */
	public function addProperty ($v, $isStatic = false) {
		if ($isStatic === null) {
			$isStatic = false;
		}
		$this->addVar($v, "protected", $isStatic);
		$this->addMethod("get" . (GeneratorTools::capitalize($v->haxeName)??'null'), [], $v->haxeType, "{ return \$this->" . $v->haxeName . "; }", "public", $isStatic);
		$this->addMethod("set" . (GeneratorTools::capitalize($v->haxeName)??'null'), [new GeneratorPhpVar($v->haxeName, $v->haxeType)], $v->haxeType, "{ \$this->" . $v->haxeName . " = " . $v->haxeName . "; }", "public", $isStatic);
	}

	/**
	 * @param GeneratorPhpVar $v
	 * @param string $access
	 * @param bool $isStatic
	 * 
	 * @return void
	 */
	public function addVar ($v, $access = "public", $isStatic = false) {
		if ($access === null) {
			$access = "public";
		}
		if ($isStatic === null) {
			$isStatic = false;
		}
		if ($v !== null) {
			$s = ((($v->haxeType !== null ? "/**\n * @var " . $v->haxeType . "\n */\n" : ""))??'null') . (($access . " ")??'null') . ((($isStatic ? "static " : ""))??'null') . "\$" . $v->haxeName . ";";
			array_push($this->vars, $s);
		} else {
			array_push($this->vars, "");
		}
	}

	/**
	 * @param string $fullClassName
	 * 
	 * @return string
	 */
	public function getPackageName ($fullClassName) {
		if ((mb_strpos($fullClassName, ".") !== false)) {
			return mb_substr($fullClassName, 0, mb_strrpos($fullClassName, "."));
		}
		return "";
	}

	/**
	 * @param string $fullClassName
	 * 
	 * @return string
	 */
	public function getShortClassName ($fullClassName) {
		if ((mb_strpos($fullClassName, ".") !== false)) {
			return mb_substr($fullClassName, mb_strrpos($fullClassName, ".") + 1, null);
		}
		return $fullClassName;
	}

	/**
	 * @param string $text
	 * @param string $ind
	 * 
	 * @return string
	 */
	public function indent ($text, $ind = "\x09") {
		if ($ind === null) {
			$ind = "\x09";
		}
		if ($text === "") {
			return "";
		}
		return $ind . (str_replace("\n", "\n" . $ind, $text)??'null');
	}

	/**
	 * @return string
	 */
	public function toString () {
		$this1 = [];
		$varLines = $this1;
		$collection = $this->vars;
		foreach ($collection as $key => $value) {
			array_push($varLines, str_replace("\n", "\n\x09", $value));
		}

		$s = "namespace " . (GeneratorTools::toPhpType($this->getPackageName($this->fullClassName), false)??'null') . ";\n" . "\n" . (implode("\n", $this->imports)??'null') . (((count($this->imports) > 0 ? "\n\n" : ""))??'null') . "class " . ($this->getShortClassName($this->fullClassName)??'null') . ((($this->baseFullClassName !== null ? " extends " . (GeneratorTools::toPhpType($this->baseFullClassName)??'null') : ""))??'null') . "\n" . "{\n" . (((count($this->vars) > 0 ? "\x09" . (implode("\n\x09\n\x09", $varLines)??'null') . "\n\n" : ""))??'null') . (((count($this->methods) > 0 ? "\x09" . (implode("\n\n\x09", $this->methods)??'null') . "\n" : ""))??'null') . (((count($this->customs) > 0 ? "\x09" . (implode("\n\n\x09", $this->customs)??'null') . "\n" : ""))??'null') . "}";
		return $s;
	}

	public function __toString() {
		return $this->toString();
	}
}

