<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

namespace nanodb\generator;

use \nanodb\php\Boot;

class StringToolsEx {
	/**
	 * @param string $s
	 * 
	 * @return string
	 */
	static public function capitalize ($s) {
		if ($s === "") {
			return $s;
		} else {
			return (mb_strtoupper(mb_substr($s, 0, 1))??'null') . (mb_substr($s, 1, null)??'null');
		}
	}
}

Boot::registerClass(StringToolsEx::class, 'generator.StringToolsEx');
