<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

namespace nanodb\sys\db;

use \nanodb\php\Boot;

interface ResultSet {
	/**
	 * @return mixed
	 */
	public function getFieldsNames () ;

	/**
	 * @param int $n
	 * 
	 * @return float
	 */
	public function getFloatResult ($n) ;

	/**
	 * @param int $n
	 * 
	 * @return int
	 */
	public function getIntResult ($n) ;

	/**
	 * @param int $n
	 * 
	 * @return string
	 */
	public function getResult ($n) ;

	/**
	 * @return int
	 */
	public function get_length () ;

	/**
	 * @return int
	 */
	public function get_nfields () ;

	/**
	 * @return bool
	 */
	public function hasNext () ;

	/**
	 * @return mixed
	 */
	public function next () ;

	/**
	 * @return mixed
	 */
	public function results () ;
}

Boot::registerClass(ResultSet::class, 'sys.db.ResultSet');
Boot::registerGetters('nanodb\\sys\\db\\ResultSet', [
	'nfields' => true,
	'length' => true
]);
