<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

namespace nanodb\sys\db;

use \nanodb\sys\db\SQLiteConnection as DbSQLiteConnection;
use \nanodb\sys\db\Connection as DbConnection;

class Sqlite {
	/**
	 * @param string $file
	 * 
	 * @return DbConnection
	 */
	static public function open ($file) {
		return new DbSQLiteConnection($file);
	}
}

