<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

namespace nanodb\sys\db;

use \nanodb\php\Boot;
use \nanodb\sys\db\_Sqlite\SQLiteConnection;
use \nanodb\sys\db\Connection as DbConnection;

class Sqlite {
	/**
	 * @param string $file
	 * 
	 * @return DbConnection
	 */
	static public function open ($file) {
		return new SQLiteConnection($file);
	}
}

Boot::registerClass(Sqlite::class, 'sys.db.Sqlite');
